export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const GET_OVERALL_STATS_DATA = "GET_OVERALL_STATS_DATA";
export const SELECTED_COUNTRY = "SELECTED_COUNTRY";
export const GET_SELECTED_COUNTRY_DATA = "GET_SELECTED_COUNTRY_DATA";
